/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzf_sdiff_SdiffHelper */

#ifndef _Included_com_wzf_sdiff_SdiffHelper
#define _Included_com_wzf_sdiff_SdiffHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzf_sdiff_SdiffHelper
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wzf_sdiff_SdiffHelper_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
